services:
  - type: web
    name: django-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: daphne quizzler.asgi:application
    autoDeploy: true  # optional

    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: quizzler.settings
      - key: ALLOWED_HOSTS
        value: cs161-quizzler.onrender.com
      - key: SECRET_KEY
        value: your-secret-key-here  # ✅ Replace with a secure, random string (use `secrets.token_urlsafe(50)`)
      - key: DEBUG
        value: "False"  # Keep as "True" temporarily if debugging
