# Generated by Django 5.2 on 2025-05-14 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_game_session', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='shield_active',
            field=models.BooleanField(default=False),
        ),
    ]
