# Generated by Django 5.2 on 2025-05-15 21:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_game_session', '0002_player_shield_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='session_code',
            field=models.CharField(db_collation='utf8mb4_bin', max_length=6, unique=True, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(6)]),
        ),
    ]
