# Generated by Django 5.2 on 2025-04-18 00:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.CharField(blank=True, default='', max_length=5000, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(5000)]),
        ),
    ]
